[project]
name = "reading-estimation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "rhoknp>=1.8.0",
    "ruff>=0.14.14",
    "torch>=2.10.0",
    "transformers>=5.0.0",
]
